# Generated by Django 4.1.7 on 2023-03-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_suit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuit',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
