# Generated by Django 4.1.7 on 2023-03-10 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_suit', '0002_alter_testsuit_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('steps', models.TextField(max_length=1000)),
                ('expected', models.TextField(max_length=1000)),
                ('actual', models.TextField(max_length=1000)),
                ('comments', models.TextField(max_length=1000)),
                ('env', models.CharField(choices=[('chrome', 'Chrome'), ('safari', 'Safari'), ('firefox', 'Firefox'), ('ios', 'Ios'), ('android', 'Android')], default='chrome', max_length=255)),
                ('status', models.CharField(choices=[('not_processed', 'Not Processed'), ('fail', 'Fail'), ('passes', 'Passes'), ('fixed', 'Fixed'), ('not_bug', 'Not Bug')], default='not_processed', max_length=255)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('link', models.CharField(max_length=255)),
                ('test_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_suit.testsuit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
